name: No Emoji Check

on:
  pull_request:
    branches: [ main, develop, codex, issues, f01.1 ]

jobs:
  no-emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for emojis in code
        run: |
          if grep -rI --color=always -P '[\p{So}\p{Cn}\x{1F600}-\x{1F64F}]' .; then
            echo "Emoji detected in code!"
            exit 1
          else
            echo "No emojis in code."
          fi

      - name: Check for emojis in commit messages
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:%s |
          grep -qP '[\p{So}\p{Cn}\x{1F600}-\x{1F64F}]' &&
          (echo "Emoji detected in commit messages!" && exit 1) ||
          echo "No emojis in commit messages."